services:
  ollama:
    image: ollama/ollama:latest
    container_name: lego_ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ../data/ollama:/root/.ollama
