services:
  caddy:
    image: caddy:2
    container_name: lego-caddy
    ports:
      - "80:80"
    volumes:
      - ./modules/proxy-caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./data/caddy_config:/config
    networks: [lego]
